### ISSUE TITLE
MJProgressView高度问题

### ISSUE THREAD

**Issue by tangbing** [CoderMJLee/MJDownload#5]
下载进度提示MJProgressView的高度，为啥为2，没看到你设置高度呀！只看懂了调用progress的set方法中再调用绘图，设置颜色与宽度。

**Comment by LarryEmerson** [comment]
他使用的是Main.storyboard,不是纯代码

**Comment by tangbing** [comment]
@LarryEmerson ,多谢提醒，看到了
